name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: Samo141988/imgtool
        ref: master
        path: imgtool
        show-progress: false
        fetch-depth: 1

    

        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl curl lz4 -y
        sudo aptitude install libssl-dev -y
        bash imgtool/img/img.sh
      
    
    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: ImgTool
        path: imj/*
        compression-level: 9
