name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        
        show-progress: false
        fetch-depth: 1

    

        
        
    - name: Prepare dependencies
      run: |
        
        bash $(pwd)/img.sh
        
    
    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: ImgTool
        path: img/*
        compression-level: 9
