name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: Samo141988/imgtool
        ref: master
        path: img
        show-progress: false
        fetch-depth: 1

    

        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install cpio git tar curl lz4 -y
        
        bash $(pwd)/img.sh
      
    
    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: ImgTool
        path: img/*
        compression-level: 9
