name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    

    - name: Install dependencies
      run: make

    
 - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: ImgTool
        path: imjtool/*
        compression-level: 9
